
//! Autogenerated weights for `pallet_plim_oracle`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: 2026-04-18, STEPS: `20`, REPEAT: `5`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `tools-aifirst-v1`, CPU: `Intel Xeon Processor (Skylake, IBRS, no TSX)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// /opt/plimlab/plim-protocol/plim-chain/target/release/plim-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet-plim-oracle
// --extrinsic
// *
// --steps
// 20
// --repeat
// 5
// --output
// /tmp/bench_out/pallet-plim-oracle.weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

pub trait WeightInfo {
	fn propose_rate() -> Weight;
	fn add_updater() -> Weight;
	fn remove_updater() -> Weight;
	fn set_quorum() -> Weight;
}

/// Weights from real frame-omni-bencher run (steps=20, repeat=5).
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn propose_rate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `202`
		//  Estimated: `6094`
		// Minimum execution time: 57_113_000 picoseconds.
		Weight::from_parts(59_938_000, 0)
			.saturating_add(Weight::from_parts(0, 6094))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	fn add_updater() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `53`
		//  Estimated: `1806`
		// Minimum execution time: 31_575_000 picoseconds.
		Weight::from_parts(34_703_000, 0)
			.saturating_add(Weight::from_parts(0, 1806))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn remove_updater() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `88`
		//  Estimated: `1806`
		// Minimum execution time: 32_907_000 picoseconds.
		Weight::from_parts(34_656_000, 0)
			.saturating_add(Weight::from_parts(0, 1806))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	fn set_quorum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `88`
		//  Estimated: `1806`
		// Minimum execution time: 18_801_000 picoseconds.
		Weight::from_parts(19_944_000, 0)
			.saturating_add(Weight::from_parts(0, 1806))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

/// Default `()` impl for tests/mocks (same numbers as SubstrateWeight).
impl WeightInfo for () {
	fn propose_rate() -> Weight { Weight::from_parts(59_938_000, 0) }
	fn add_updater() -> Weight { Weight::from_parts(34_703_000, 0) }
	fn remove_updater() -> Weight { Weight::from_parts(34_656_000, 0) }
	fn set_quorum() -> Weight { Weight::from_parts(19_944_000, 0) }
}
