
//! Autogenerated weights for `pallet_plim_mesh_relay`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: 2026-05-14, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `plimagentserver`, CPU: `Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/plim-node
// benchmark
// pallet
// --pallet
// pallet-plim-mesh-relay
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/plim-mesh-relay/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_plim_mesh_relay`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_plim_mesh_relay::WeightInfo for WeightInfo<T> {
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `PlimMeshRelay::RelayedHashIndex` (r:1 w:1)
	/// Proof: `PlimMeshRelay::RelayedHashIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `PlimMeshRelay::RelayedTransactions` (r:1 w:1)
	/// Proof: `PlimMeshRelay::RelayedTransactions` (`max_values`: Some(1), `max_size`: Some(12020002), added: 12020497, mode: `MaxEncodedLen`)
	fn submit_relayed_transaction() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `72`
		//  Estimated: `12021487`
		// Minimum execution time: 55_143_000 picoseconds.
		Weight::from_parts(56_753_000, 0)
			.saturating_add(Weight::from_parts(0, 12021487))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
