
//! Autogenerated weights for `pallet_plim_kyc`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: 2026-04-18, STEPS: `20`, REPEAT: `5`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `tools-aifirst-v1`, CPU: `Intel Xeon Processor (Skylake, IBRS, no TSX)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// /opt/plimlab/plim-protocol/plim-chain/target/release/plim-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet-plim-kyc
// --extrinsic
// *
// --steps
// 20
// --repeat
// 5
// --output
// /tmp/bench_out/pallet-plim-kyc.weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

pub trait WeightInfo {
	fn set_kyc() -> Weight;
	fn revoke_kyc() -> Weight;
	fn add_attestor() -> Weight;
	fn remove_attestor() -> Weight;
	fn add_to_sanction_list() -> Weight;
	fn remove_from_sanction_list() -> Weight;
}

/// Weights from real frame-omni-bencher run (steps=20, repeat=5).
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn set_kyc() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `63`
		//  Estimated: `3514`
		// Minimum execution time: 26_924_000 picoseconds.
		Weight::from_parts(32_413_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn revoke_kyc() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `97`
		//  Estimated: `2126`
		// Minimum execution time: 42_788_000 picoseconds.
		Weight::from_parts(47_517_000, 0)
			.saturating_add(Weight::from_parts(0, 2126))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn add_attestor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `28`
		//  Estimated: `2126`
		// Minimum execution time: 25_155_000 picoseconds.
		Weight::from_parts(26_967_000, 0)
			.saturating_add(Weight::from_parts(0, 2126))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn remove_attestor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `63`
		//  Estimated: `2126`
		// Minimum execution time: 27_087_000 picoseconds.
		Weight::from_parts(28_607_000, 0)
			.saturating_add(Weight::from_parts(0, 2126))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn add_to_sanction_list() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `28`
		//  Estimated: `3588`
		// Minimum execution time: 40_387_000 picoseconds.
		Weight::from_parts(43_647_000, 0)
			.saturating_add(Weight::from_parts(0, 3588))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn remove_from_sanction_list() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 26_667_000 picoseconds.
		Weight::from_parts(27_574_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

/// Default `()` impl for tests/mocks (same numbers as SubstrateWeight).
impl WeightInfo for () {
	fn set_kyc() -> Weight { Weight::from_parts(32_413_000, 0) }
	fn revoke_kyc() -> Weight { Weight::from_parts(47_517_000, 0) }
	fn add_attestor() -> Weight { Weight::from_parts(26_967_000, 0) }
	fn remove_attestor() -> Weight { Weight::from_parts(28_607_000, 0) }
	fn add_to_sanction_list() -> Weight { Weight::from_parts(43_647_000, 0) }
	fn remove_from_sanction_list() -> Weight { Weight::from_parts(27_574_000, 0) }
}
