//! Autogenerated weights for pallet-plim-royalties (placeholder).
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI.
//! Manual edits will be lost on re-generation.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::weights::Weight;

/// Weight functions needed for pallet-plim-royalties.
pub trait WeightInfo {
	fn claim_accumulated_royalties() -> Weight;
	fn set_platform_treasury() -> Weight;
	fn update_platform_fee() -> Weight;
}

/// Placeholder weights — replace with benchmarked values before mainnet.
pub struct SubstrateWeight;

impl WeightInfo for SubstrateWeight {
	fn claim_accumulated_royalties() -> Weight {
		Weight::from_parts(15_000, 0)
	}

	fn set_platform_treasury() -> Weight {
		Weight::from_parts(10_000, 0)
	}

	fn update_platform_fee() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}

/// Unit-test / default implementation.
impl WeightInfo for () {
	fn claim_accumulated_royalties() -> Weight {
		Weight::from_parts(15_000, 0)
	}

	fn set_platform_treasury() -> Weight {
		Weight::from_parts(10_000, 0)
	}

	fn update_platform_fee() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}
