
//! Autogenerated weights for `pallet_rwa`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: 2026-04-18, STEPS: `20`, REPEAT: `5`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `tools-aifirst-v1`, CPU: `Intel Xeon Processor (Skylake, IBRS, no TSX)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// /opt/plimlab/plim-protocol/plim-chain/target/release/plim-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet-rwa
// --extrinsic
// register_asset,mint_shares,burn_shares,transfer_shares,freeze,unfreeze,wind_down
// --steps
// 20
// --repeat
// 5
// --output
// /tmp/bench_out/pallet-rwa.weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

pub trait WeightInfo {
	fn register_asset() -> Weight;
	fn mint_shares() -> Weight;
	fn burn_shares() -> Weight;
	fn transfer_shares() -> Weight;
	fn distribute_yield() -> Weight;
	fn claim_yield() -> Weight;
	fn claim_all_yield() -> Weight;
	fn freeze() -> Weight;
	fn unfreeze() -> Weight;
	fn wind_down() -> Weight;
}

/// Weights from real frame-omni-bencher run (steps=20, repeat=5).
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn register_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3721`
		// Minimum execution time: 26_157_000 picoseconds.
		Weight::from_parts(28_188_000, 0)
			.saturating_add(Weight::from_parts(0, 3721))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	fn mint_shares() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `193`
		//  Estimated: `3721`
		// Minimum execution time: 38_188_000 picoseconds.
		Weight::from_parts(39_011_000, 0)
			.saturating_add(Weight::from_parts(0, 3721))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	fn burn_shares() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `245`
		//  Estimated: `3721`
		// Minimum execution time: 37_903_000 picoseconds.
		Weight::from_parts(45_557_000, 0)
			.saturating_add(Weight::from_parts(0, 3721))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	fn transfer_shares() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299`
		//  Estimated: `3721`
		// Minimum execution time: 40_191_000 picoseconds.
		Weight::from_parts(78_009_000, 0)
			.saturating_add(Weight::from_parts(0, 3721))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn distribute_yield() -> Weight {
		// Placeholder: benchmark failed at runtime; using conservative 10_000.
		Weight::from_parts(10_000, 0)
	}
	fn claim_yield() -> Weight {
		// Placeholder: benchmark failed at runtime; using conservative 10_000.
		Weight::from_parts(10_000, 0)
	}
	fn claim_all_yield() -> Weight {
		// Placeholder: benchmark failed at runtime; using conservative 10_000.
		Weight::from_parts(10_000, 0)
	}
	fn freeze() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `82`
		//  Estimated: `3721`
		// Minimum execution time: 24_106_000 picoseconds.
		Weight::from_parts(25_017_000, 0)
			.saturating_add(Weight::from_parts(0, 3721))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn unfreeze() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `124`
		//  Estimated: `3721`
		// Minimum execution time: 27_572_000 picoseconds.
		Weight::from_parts(32_200_000, 0)
			.saturating_add(Weight::from_parts(0, 3721))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn wind_down() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `82`
		//  Estimated: `3721`
		// Minimum execution time: 24_732_000 picoseconds.
		Weight::from_parts(25_997_000, 0)
			.saturating_add(Weight::from_parts(0, 3721))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

/// Default `()` impl for tests/mocks (same numbers as SubstrateWeight).
impl WeightInfo for () {
	fn register_asset() -> Weight { Weight::from_parts(28_188_000, 0) }
	fn mint_shares() -> Weight { Weight::from_parts(39_011_000, 0) }
	fn burn_shares() -> Weight { Weight::from_parts(45_557_000, 0) }
	fn transfer_shares() -> Weight { Weight::from_parts(78_009_000, 0) }
	fn distribute_yield() -> Weight { Weight::from_parts(10_000, 0) }
	fn claim_yield() -> Weight { Weight::from_parts(10_000, 0) }
	fn claim_all_yield() -> Weight { Weight::from_parts(10_000, 0) }
	fn freeze() -> Weight { Weight::from_parts(25_017_000, 0) }
	fn unfreeze() -> Weight { Weight::from_parts(32_200_000, 0) }
	fn wind_down() -> Weight { Weight::from_parts(25_997_000, 0) }
}
