//! Autogenerated weights placeholder for pallet-plim-marketplace.
//!
//! Replace with real benchmarking output once `frame-benchmarking` runs are done.

use frame_support::weights::Weight;

pub trait WeightInfo {
	fn list_for_sale() -> Weight;
	fn cancel_listing() -> Weight;
	fn buy_now() -> Weight;
	fn buy_now_with_fiat_proof() -> Weight;
	fn make_offer() -> Weight;
	fn accept_offer() -> Weight;
	fn reject_offer() -> Weight;
	fn withdraw_offer() -> Weight;
	fn update_platform_fee() -> Weight;
}

/// Placeholder weights — all set to 10_000 weight units.
pub struct SubstrateWeight;

impl WeightInfo for SubstrateWeight {
	fn list_for_sale() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn cancel_listing() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn buy_now() -> Weight {
		Weight::from_parts(20_000, 0)
	}
	fn buy_now_with_fiat_proof() -> Weight {
		Weight::from_parts(15_000, 0)
	}
	fn make_offer() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn accept_offer() -> Weight {
		Weight::from_parts(15_000, 0)
	}
	fn reject_offer() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn withdraw_offer() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn update_platform_fee() -> Weight {
		Weight::from_parts(5_000, 0)
	}
}

impl WeightInfo for () {
	fn list_for_sale() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn cancel_listing() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn buy_now() -> Weight {
		Weight::from_parts(20_000, 0)
	}
	fn buy_now_with_fiat_proof() -> Weight {
		Weight::from_parts(15_000, 0)
	}
	fn make_offer() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn accept_offer() -> Weight {
		Weight::from_parts(15_000, 0)
	}
	fn reject_offer() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn withdraw_offer() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn update_platform_fee() -> Weight {
		Weight::from_parts(5_000, 0)
	}
}
