
//! Autogenerated weights for `pallet_plim_marketplace`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: 2026-04-18, STEPS: `20`, REPEAT: `5`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `tools-aifirst-v1`, CPU: `Intel Xeon Processor (Skylake, IBRS, no TSX)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// /opt/plimlab/plim-protocol/plim-chain/target/release/plim-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet-plim-marketplace
// --extrinsic
// *
// --steps
// 20
// --repeat
// 5
// --output
// ./pallets/plim-marketplace/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

pub trait WeightInfo {
	fn list_for_sale() -> Weight;
	fn cancel_listing() -> Weight;
	fn buy_now() -> Weight;
	fn buy_now_with_fiat_proof() -> Weight;
	fn make_offer() -> Weight;
	fn accept_offer() -> Weight;
	fn reject_offer() -> Weight;
	fn withdraw_offer() -> Weight;
	fn update_platform_fee() -> Weight;
	fn create_auction() -> Weight;
	fn bid_auction() -> Weight;
	fn settle_auction() -> Weight;
	fn cancel_auction() -> Weight;
}

/// Weights from real frame-omni-bencher run (steps=20, repeat=5).
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn list_for_sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 811_000 picoseconds.
		Weight::from_parts(829_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn cancel_listing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 652_000 picoseconds.
		Weight::from_parts(829_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn buy_now() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 817_000 picoseconds.
		Weight::from_parts(828_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn buy_now_with_fiat_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 386_000 picoseconds.
		Weight::from_parts(828_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn make_offer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 811_000 picoseconds.
		Weight::from_parts(851_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn accept_offer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 636_000 picoseconds.
		Weight::from_parts(913_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn reject_offer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 474_000 picoseconds.
		Weight::from_parts(887_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn withdraw_offer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 593_000 picoseconds.
		Weight::from_parts(923_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn update_platform_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 386_000 picoseconds.
		Weight::from_parts(873_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn create_auction() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 799_000 picoseconds.
		Weight::from_parts(820_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn bid_auction() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 333_000 picoseconds.
		Weight::from_parts(394_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn settle_auction() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 815_000 picoseconds.
		Weight::from_parts(842_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn cancel_auction() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 425_000 picoseconds.
		Weight::from_parts(1_021_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}

/// Default `()` impl for tests/mocks (same numbers as SubstrateWeight).
impl WeightInfo for () {
	fn list_for_sale() -> Weight { Weight::from_parts(829_000, 0) }
	fn cancel_listing() -> Weight { Weight::from_parts(829_000, 0) }
	fn buy_now() -> Weight { Weight::from_parts(828_000, 0) }
	fn buy_now_with_fiat_proof() -> Weight { Weight::from_parts(828_000, 0) }
	fn make_offer() -> Weight { Weight::from_parts(851_000, 0) }
	fn accept_offer() -> Weight { Weight::from_parts(913_000, 0) }
	fn reject_offer() -> Weight { Weight::from_parts(887_000, 0) }
	fn withdraw_offer() -> Weight { Weight::from_parts(923_000, 0) }
	fn update_platform_fee() -> Weight { Weight::from_parts(873_000, 0) }
	fn create_auction() -> Weight { Weight::from_parts(820_000, 0) }
	fn bid_auction() -> Weight { Weight::from_parts(394_000, 0) }
	fn settle_auction() -> Weight { Weight::from_parts(842_000, 0) }
	fn cancel_auction() -> Weight { Weight::from_parts(1_021_000, 0) }
}
